import type { Property } from './types'

export const properties: Property[] = [
  {
    slug: 'furnished-2bed-east-legon',
    title: 'Furnished 2-Bedroom Apartment in East Legon',
    description:
      'Beautiful fully-furnished 2-bedroom apartment in a secure estate in East Legon. The apartment features modern finishes, air conditioning in all rooms, 24-hour security, backup generator, and reliable borehole water. Walking distance to East Legon shops and restaurants. No agents — contact the owner directly.',
    type: 'apartment',
    status: 'available',
    neighborhood: 'East Legon',
    city: 'Accra',
    price_ghs: 4500,
    advance_months: 12,
    bedrooms: 2,
    bathrooms: 2,
    size_sqm: 95,
    furnished: true,
    features: ['Generator', '24h Water', 'Air Conditioning', 'Security', 'DSTV Ready', 'Balcony', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
    ],
    owner: { name: 'Kwame Asante', phone: '233244123456', initials: 'KA', verified_phone: true, verified_card: true, joined_year: 2023, response_rate: 98 },
    verification_level: 'full',
    views: 342,
    inquiries: 18,
    listed_date: '2026-06-10',
  },
  {
    slug: 'spacious-3bed-house-spintex',
    title: 'Spacious 3-Bedroom House with Garden — Spintex',
    description:
      "Large 3-bedroom detached house on Spintex Road. The compound includes a boys' quarters, private garden, and garage. The house has been freshly painted and features ceramic tiled floors throughout. The owner lives nearby and can show the property at any time. Serious tenants only.",
    type: 'house',
    status: 'available',
    neighborhood: 'Spintex Road',
    city: 'Accra',
    price_ghs: 5500,
    advance_months: 12,
    bedrooms: 3,
    bathrooms: 2,
    size_sqm: 180,
    furnished: false,
    features: ['Generator', 'Borehole Water', 'Boys Quarters', 'Garden', 'Garage', 'Security', 'Tiled Floors'],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
    ],
    owner: { name: 'Abena Mensah', phone: '233208765432', initials: 'AM', verified_phone: true, verified_card: true, joined_year: 2024, response_rate: 95 },
    verification_level: 'full',
    views: 521,
    inquiries: 27,
    listed_date: '2026-06-01',
  },
  {
    slug: 'self-contained-chamber-adenta',
    title: 'Self-Contained Chamber & Hall — Adenta',
    description:
      'Clean self-contained chamber and hall in a quiet compound at Adenta. Has its own bathroom and kitchen. Running water from borehole. Located close to Adenta Market and transport. Suitable for a young professional or couple. No agents — owner lives on site.',
    type: 'chamber_and_hall',
    status: 'available',
    neighborhood: 'Adenta',
    city: 'Accra',
    price_ghs: 1400,
    advance_months: 12,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 35,
    furnished: false,
    features: ['Borehole Water', 'Own Bathroom', 'Own Kitchen', 'Security Gate'],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
    ],
    owner: { name: 'Kofi Boateng', phone: '233276543210', initials: 'KB', verified_phone: true, verified_card: false, joined_year: 2025, response_rate: 87 },
    verification_level: 'phone',
    views: 189,
    inquiries: 14,
    listed_date: '2026-06-18',
  },
  {
    slug: 'modern-1bed-airport-residential',
    title: 'Modern 1-Bedroom Apartment — Airport Residential',
    description:
      'Stylish 1-bedroom apartment in the prestigious Airport Residential area. Fully air-conditioned with modern kitchen fittings. The building has 24-hour security, CCTV, and a parking lot. Ideal for an expat or young professional. Contact owner directly — no agents involved.',
    type: 'apartment',
    status: 'available',
    neighborhood: 'Airport Residential',
    city: 'Accra',
    price_ghs: 3800,
    advance_months: 6,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 65,
    furnished: true,
    features: ['Air Conditioning', '24h Security', 'CCTV', 'Parking', 'Generator', '24h Water', 'Fiber Internet'],
    images: [
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=900&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
    ],
    owner: { name: 'Ama Darko', phone: '233201234567', initials: 'AD', verified_phone: true, verified_card: true, joined_year: 2024, response_rate: 100 },
    verification_level: 'full',
    views: 614,
    inquiries: 31,
    listed_date: '2026-05-28',
  },
  {
    slug: '4bed-executive-house-cantonments',
    title: '4-Bedroom Executive House — Cantonments',
    description:
      "Executive 4-bedroom house in one of Accra's most sought-after neighbourhoods. Comes with domestic staff quarters, large garden, swimming pool, and double garage. All bedrooms are ensuite. Ideal for senior executives, embassy staff, or families. Price is firm — no agents.",
    type: 'house',
    status: 'available',
    neighborhood: 'Cantonments',
    city: 'Accra',
    price_ghs: 9500,
    advance_months: 12,
    bedrooms: 4,
    bathrooms: 4,
    size_sqm: 380,
    furnished: false,
    features: ['Swimming Pool', 'Garden', 'Double Garage', 'Generator', 'Borehole Water', 'DSTV', 'Air Conditioning', 'Staff Quarters', '24h Security'],
    images: [
      'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=900&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80',
    ],
    owner: { name: 'Nana Osei', phone: '233244987654', initials: 'NO', verified_phone: true, verified_card: true, joined_year: 2023, response_rate: 92 },
    verification_level: 'full',
    views: 897,
    inquiries: 43,
    listed_date: '2026-05-15',
  },
  {
    slug: '2bed-apartment-tema-community-9',
    title: '2-Bedroom Apartment — Tema Community 9',
    description:
      'Comfortable 2-bedroom apartment in Tema Community 9. Close to major markets, schools, and transport links to Accra. The apartment has tiled floors, its own water meter, and access to a shared generator. Unfurnished and ready to move in. Owner contact only.',
    type: 'apartment',
    status: 'available',
    neighborhood: 'Tema Community 9',
    city: 'Tema',
    price_ghs: 2800,
    advance_months: 12,
    bedrooms: 2,
    bathrooms: 1,
    size_sqm: 80,
    furnished: false,
    features: ['Generator', 'Tiled Floors', 'Own Water Meter', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
    ],
    owner: { name: 'Yaw Frimpong', phone: '233209876543', initials: 'YF', verified_phone: true, verified_card: false, joined_year: 2025, response_rate: 82 },
    verification_level: 'phone',
    views: 278,
    inquiries: 16,
    listed_date: '2026-06-14',
  },
  {
    slug: '3bed-apartment-labone',
    title: '3-Bedroom Apartment with Pool — Labone',
    description:
      'Luxurious 3-bedroom apartment in a gated complex in Labone. Features a rooftop swimming pool, gym, 24-hour concierge, and underground parking. High-speed internet included. All rooms are large and well-ventilated. Currently occupied — available from August 2026.',
    type: 'apartment',
    status: 'rented',
    neighborhood: 'Labone',
    city: 'Accra',
    price_ghs: 7500,
    advance_months: 6,
    bedrooms: 3,
    bathrooms: 3,
    size_sqm: 160,
    furnished: true,
    features: ['Swimming Pool', 'Gym', 'Concierge', 'Underground Parking', 'Fiber Internet', 'Air Conditioning', 'Generator'],
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=900&q=80',
    ],
    owner: { name: 'Efua Sarpong', phone: '233244111222', initials: 'ES', verified_phone: true, verified_card: true, joined_year: 2023, response_rate: 97 },
    verification_level: 'full',
    views: 1102,
    inquiries: 54,
    listed_date: '2026-04-20',
  },
  {
    slug: '1bed-apartment-madina',
    title: '1-Bedroom Apartment — Madina Zongo Junction',
    description:
      'Affordable 1-bedroom apartment near Madina Zongo Junction. Has its own bathroom, kitchen space, and veranda. The compound is clean and has reliable borehole water. Close to Madina Market and trotro stations. Great for students or young professionals. Speak to owner directly.',
    type: 'apartment',
    status: 'available',
    neighborhood: 'Madina',
    city: 'Accra',
    price_ghs: 1600,
    advance_months: 12,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 40,
    furnished: false,
    features: ['Borehole Water', 'Veranda', 'Close to Market', 'Security Gate'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
    ],
    owner: { name: 'Akosua Acheampong', phone: '233277334455', initials: 'AA', verified_phone: true, verified_card: false, joined_year: 2026, response_rate: 79 },
    verification_level: 'phone',
    views: 203,
    inquiries: 19,
    listed_date: '2026-06-20',
  },
  {
    slug: '2bed-house-ashaiman',
    title: '2-Bedroom House — Ashaiman',
    description:
      'Decent 2-bedroom house in Ashaiman with its own compound. Has space for parking a vehicle. Close to Ashaiman Market and main road. The house is quiet and in a low-crime area. Unfurnished. Borehole water available. Price negotiable for the right tenant.',
    type: 'house',
    status: 'available',
    neighborhood: 'Ashaiman',
    city: 'Tema',
    price_ghs: 2000,
    advance_months: 12,
    bedrooms: 2,
    bathrooms: 1,
    size_sqm: 70,
    furnished: false,
    features: ['Borehole Water', 'Private Compound', 'Parking', 'Price Negotiable'],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
    ],
    owner: { name: 'Emmanuel Tetteh', phone: '233205554433', initials: 'ET', verified_phone: true, verified_card: true, joined_year: 2025, response_rate: 88 },
    verification_level: 'full',
    views: 167,
    inquiries: 11,
    listed_date: '2026-06-22',
  },
  {
    slug: '3bed-semi-detached-haatso',
    title: '3-Bedroom Semi-Detached House — Haatso',
    description:
      'Well-maintained 3-bedroom semi-detached house in Haatso. Two of the three bedrooms are ensuite. Has its own compound and a dedicated parking spot. Located on a quiet street, 10 minutes from the Accra-Kumasi highway. Tiled throughout, repainted 2025. No agents.',
    type: 'house',
    status: 'available',
    neighborhood: 'Haatso',
    city: 'Accra',
    price_ghs: 3200,
    advance_months: 12,
    bedrooms: 3,
    bathrooms: 2,
    size_sqm: 130,
    furnished: false,
    features: ['Tiled Floors', 'Parking', 'Borehole Water', 'Generator', 'Quiet Street', '2 Ensuite Rooms'],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80',
    ],
    owner: { name: 'Grace Amponsah', phone: '233243667788', initials: 'GA', verified_phone: true, verified_card: true, joined_year: 2024, response_rate: 93 },
    verification_level: 'full',
    views: 389,
    inquiries: 22,
    listed_date: '2026-06-05',
  },
  {
    slug: 'studio-apartment-osu',
    title: 'Modern Studio Apartment — Osu',
    description:
      'Compact, fully-furnished studio apartment in the heart of Osu. Includes kitchenette, AC, and fast Wi-Fi. The building has 24-hour security and is within walking distance of Oxford Street restaurants and shops. Ideal for a single professional or expat on a short-term stay.',
    type: 'studio',
    status: 'available',
    neighborhood: 'Osu',
    city: 'Accra',
    price_ghs: 2200,
    advance_months: 6,
    bedrooms: 0,
    bathrooms: 1,
    size_sqm: 30,
    furnished: true,
    features: ['Air Conditioning', 'Fiber Internet', '24h Security', 'DSTV', 'Kitchenette', 'Walking Distance to Restaurants'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
    ],
    owner: { name: 'Kwesi Hammond', phone: '233261223344', initials: 'KH', verified_phone: true, verified_card: true, joined_year: 2024, response_rate: 99 },
    verification_level: 'full',
    views: 741,
    inquiries: 38,
    listed_date: '2026-05-30',
  },
  {
    slug: '2bed-apartment-achimota',
    title: '2-Bedroom Apartment — Achimota',
    description:
      'Spacious 2-bedroom apartment near Achimota School junction. Both bedrooms have built-in wardrobes. The apartment is on the top floor with good ventilation. The compound has a borehole and shared generator. Easy access to public transport to Accra CBD. Owner-direct — no agent fees.',
    type: 'apartment',
    status: 'available',
    neighborhood: 'Achimota',
    city: 'Accra',
    price_ghs: 2400,
    advance_months: 12,
    bedrooms: 2,
    bathrooms: 1,
    size_sqm: 85,
    furnished: false,
    features: ['Borehole Water', 'Generator', 'Built-in Wardrobes', 'Top Floor', 'Good Ventilation'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
    ],
    owner: { name: 'Abigail Owusu', phone: '233248990011', initials: 'AO', verified_phone: true, verified_card: false, joined_year: 2025, response_rate: 84 },
    verification_level: 'phone',
    views: 256,
    inquiries: 15,
    listed_date: '2026-06-12',
  },
]

export const neighborhoods = [
  'East Legon', 'Spintex Road', 'Airport Residential', 'Cantonments',
  'Labone', 'Osu', 'Adenta', 'Haatso', 'Madina', 'Achimota',
  'Tema Community 9', 'Ashaiman', 'Dansoman', 'Kasoa',
]

export const propertyTypes = [
  { value: 'apartment',        label: 'Apartment' },
  { value: 'house',            label: 'House' },
  { value: 'chamber_and_hall', label: 'Chamber & Hall' },
  { value: 'studio',           label: 'Studio' },
  { value: 'townhouse',        label: 'Townhouse' },
]
